### ISSUE TITLE
cointracking.info format should include fees in sell amount

### ISSUE THREAD

**Issue by Mylros** [hodgerpodger/staketaxcsv#31]
cointracking.info format does not include fees in sell amount.
Sell amount should include the fees.
https://cointracking.freshdesk.com/en/support/solutions/articles/29000007202-entering-fees

Sell amount 178 should be 178.287933
<img width="492" alt="csv" src="https://user-images.githubusercontent.com/20350385/149640728-10ddd606-0019-4e0a-a3e8-a1d6213a7a0a.png">

**Comment by fentas** [comment]
Uh, good catch. Also to note is that it is quite common that within the terra space ppl pay fees in third currency (e.g. UST, KRT) this is important:

> Any fee that is paid in a third currency (i.e. a coin that is not part of either the sell or the buy) is not deducted from the total balance. A common example is BNB on Binance.
> In order to correct your third coin balance in the portfolio, you need to create an additional transaction as OTHER FEE for the fee.

**Comment by hodgerpodger** [comment]
Oi, wish I didn't agree after some inspection. But looks like this is the case.  

Though fix shouldn't be too complicated, I'll probably take some time to verify/test on this one due to significant impact to many website users.

**Comment by hodgerpodger** [comment]
fixed with https://github.com/hodgerpodger/staketaxcsv/commit/6a1c25340ce6ca2367ca6e37cf583d97e3645f21  and deployed.

**Comment by Mylros** [comment]
Just tested it, looks good. Thanks for the update, it's very helpful.
The issue @fentas mentioned (fees in third currency) is still not implemented. 
Should we open a new issue to track that?

**Comment by hodgerpodger** [comment]
I think the above fix includes fees in third currency (at least intended)?  Let me know if there's an issue or misunderstanding I don't see.

**Comment by Mylros** [comment]
Thanks! 
You are correct, maybe I was using a cached version. 

I did found another small issue. 
For example see transaction (Not my wallet, I wish LOL)
https://finder.terra.money/mainnet/tx/27883FBC26377D764AD259E5CBF41F9CC04738C80EF850B7E270F32758ABD5DE

In cointracking format, sometimes it seems the buy or sell amount in UST the math is off by 0.00000001

buy amount in default csv = 3450865.787619 
fee: 0.250657

Buy amount in cointracking csv should be, buy amount in default csv - fee
3450865.787619 - 0.250657 = 3450865.**536962**


Buy amount in cointracking csv: 3450865.**53696199**
![image](https://user-images.githubusercontent.com/20350385/150727410-b8a33904-6a52-4546-8994-6b14b5ab731b.png)
